# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e33daa4f544bca04f349d7188b68c4f03cfb901f274c144e2c745b6b6888e515cc1a87835de08fd20dda36245e062e323bae571cda536cf360da64e67017968c

test:
  secret_key_base: db96939b25afe166b0634fd4469988cd3af868875ea5f1523927f1c3a441eab390ed99761fa33cf6975935834f20d5489b8385c3dfe6ce9d02c8bc99ab0b7078

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
